name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish-java-versioning:
    uses: ./.github/workflows/java-release.yaml
    with:
      generateRelease: false
    secrets: inherit
  generate-release:
    needs: publish-java-versioning
    uses: ./.github/workflows/create-release.yaml
    secrets: inherit
