name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish-java-versioning:
    uses: nimbox/build-tools/.github/workflows/java-release.yaml@main
    with:
      generateRelease: false
    secrets: inherit
  generate-release:
    needs: [publish-java-versioning]
    uses: nimbox/build-tools/.github/workflows/create-release.yaml@main
    secrets: inherit
